dist: trusty
sudo: required
language: node_js
node_js:
- "8"

os:
- linux
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

jobs:
  include:
  - stage: install
    script: npm install
    skip_cleanup: true
  - stage: test
    script:
    - npm run test:lib:coverage
    - npm run report-coverage:lib
    skip_cleanup: true
  - stage: build
    script:
    - npm run build:lib
    - npm run build:demo
  - stage: release
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npm run publish
    if: branch = master
